### ISSUE TITLE
Replace std::shared_mutex in 4.24.2 ?

### ISSUE THREAD

**Issue by s-hemer** [bw2012/UnrealSandboxTerrain#6]
Any ideas how to fix the issue in i.e. kvdb.h that Unreal does not find std::shared_mutex anymore ?

**Comment by s-hemer** [comment]
Same for kvdb.hpp at master as for the submodule set to commit 368d0ae in UE4VoxelTerrain

**Comment by bw2012** [comment]
Hi. Why std::shared_mutex is not available in ue4? This is regular C++17 feature
You can try to replace in with std::mutex (c++11)

**Comment by s-hemer** [comment]
Yeah, just wondered myself. Also can't find any info on this. It suggests std::timed_mutex in the compiler output.
But there is quite some more issues, don't think I can go on today but I will report as soon as possible.

**Comment by s-hemer** [comment]
I still struggeling with the following issues:

* Source/UnrealSandboxTerrain/Public/kvdb.h:485:17: error: use of typeid requires -frtti
* Source/UnrealSandboxTerrain/Public/kvdb.h:484:8: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
* Source/UnrealSandboxTerrain/Private/qef_simd.h:154:14: error: member reference base type 'const __m128' (vector of 4 'float' values) is not a structure or union

**Comment by s-hemer** [comment]
The last one obviously is a problem of compiler as it is only available in MSVC.

**Comment by bw2012** [comment]
ok, I will check it asap

**Comment by s-hemer** [comment]
Last one fixed by quite some #ifdef _WIN32 and alternatively using direct [] operator access which should be fine with recent clang.

**Comment by RonYanDaik** [comment]
What version of VisStudio are you using?

**Comment by s-hemer** [comment]
That might be one major point I did not explicitly mention: I try to compile it under Linux, so no VisualStudio. Just make

**Comment by RonYanDaik** [comment]
> 
> 
> That might be one major point I did not explicitly mention: I try to compile it under Linux, so no VisualStudio. Just make

have you seen this?
https://stackoverflow.com/questions/36222912/is-c17-stdshared-mutex-not-available-yet

**Comment by s-hemer** [comment]
Well, Unreal brings it's own Clang/LLVM toolchain as far as I understood. It seems to be the case that there is no untimed shared_mutex. Although I tried to use the shared_timed_mutex as a first shoot, I think it would be better to look for a platform independent solution from [UE4 API](https://docs.unrealengine.com/en-US/API/Runtime/Core/HAL/index.html), i.e. FCriticalSection.

**Comment by bw2012** [comment]
I have remove all c++17 dependencies from current version but it still not ported to 4.24 yet
0d5b44474a92f0dbce8bbf50e0f1e321f2b78803
e02c7795d7803eb6c64a71b2fa732c597864a699

**Comment by s-hemer** [comment]
With the latest changes, with some minor changes from my side, there is only the two errors in kvdb.hpp:498 and :548 left:

**Comment by bw2012** [comment]
It is great. Could you please provide more info about your build environment? Windows and compiler version etc.

**Comment by s-hemer** [comment]
Kubuntu 18.04.3 and the Unreal-provided toolchain based on Clang 8.0.1 (v15_clang-8.0.1-centos7)

**Comment by s-hemer** [comment]
Removing the std::move calls in mentioned lines (as he compiler message suggests) solves all compilation problems.

Linking complains now  about "undefined symbol: typeinfo for AHUD"  (and ASandboxCharacter, AGameMode, ASandboxPlayerController, UUserWidget, ASandboxTerrainController)

**Comment by s-hemer** [comment]
Fixed it!

**Comment by s-hemer** [comment]
So my changes, especially the `#ifdef _WIN32` in Source/UnrealSandboxTerrain/Private/qef_simd.h, still work correctly under Windows? I guess, we can close it then.

**Comment by bw2012** [comment]
I have tested on win 7 and it works fine. Thank you.
